name: build-artifact
on: workflow_dispatch
jobs:
  build-and-upload:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: dir
      - run: npm install -g pkg
      - run: npx pkg . -t node18
      - run: dir build/
      - uses: actions/upload-artifact@v3
        with:
          name: heartbeat-lan-client
          path: build/heartbeatlanclient.exe

